### ISSUE TITLE
s2-init-twitter cannot be called

### ISSUE THREAD

**Issue by tmcchandra** [splix/grails-spring-security-twitter#23]
Calling s2-init-twitter results in : 

| Error Error executing script S2InitTwitter: java.lang.ClassNotFoundException: org.codehaus.groovy.grails.plugins.springsecurity.SpringSecurityUtils

The stacktrace:

java.lang.ClassNotFoundException: org.codehaus.groovy.grails.plugins.springsecurity.SpringSecurityUtils
    at java_lang_ClassLoader$loadClass.call(Unknown Source)
    at S2InitTwitter.configure(S2InitTwitter:85)
    at S2InitTwitter.this$4$configure(S2InitTwitter)
    at org.codehaus.gant.GantMetaClass.invokeMethod(GantMetaClass.java:133)
    at S2InitTwitter$_run_closure1.doCall(S2InitTwitter:36)

**Comment by splix** [comment]
Thank you. Seems that s2-init-twitter still expects old Spring Security Core plugin, 1.2.x. 

At this moment I suggest you to make Config changes manually, follow the docs: http://splix.github.io/grails-spring-security-twitter/guide/3%20Usage.html

**Comment by danhyun** [comment]
:+1:

**Comment by splix** [comment]
plugin v0.6.2
